apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-lab
  name: my-lab
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-lab
  template:
    metadata:
      labels:
        app: my-lab
    spec:
      containers:
      - image: httpd
        name: httpd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
