apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      volumes:
        - name: scratch
          emptyDir:
            sizeLimit: 500Mi
      containers:
        - image: ghcr.io/mealie-recipes/mealie:v1.10.2
          name: mealie
          ports: 
            - containerPort: 9000
          volumeMounts:
            - mountPath: /scratch
              name: scratch
